### ISSUE TITLE
Implement peer discovery

### ISSUE THREAD

**Issue by keyvank** [zeeka-network/bazuka#1]
- [x] There should be a list of bootstrap nodes somewhere. Maybe put them on a GitHub repo.
- [x] Nodes should be able to get initial nodes from bootstrap node list and discover the whole network. Nodes do this by introducing themselves through http POST requests to other nodes and discovering their peers through GET requests. This happens in a fixed interval.
- [ ] Nodes can filter the messages they want to receive from their peers through Bloom Filters. They submit their Bloom Filter in the introduction phase.

**Comment by n1rna** [comment]
would like to work on this one if it's not taken

**Comment by n1rna** [comment]
For the list of bootstrap nodes, you can check how Bitcoin does it: https://github.com/bitcoin/bitcoin/tree/master/contrib/seeds

It makes sens to not to hardcode a repository's url inside the code because the repo might be hosted on different places. the list of seed nodes can indeed be kept on a repo or any hosted page, but the list should be compiled into the node and the node should not need to fetch them from the public internet.
 
what do you think? I can work on that.

**Comment by keyvank** [comment]
Well done!

**Comment by n1rna** [comment]
As we discussed, we may not need the bloom filters for now. If they happen to come up later we can discuss the details on them again. but for now, we may close the issue :)

**Comment by keyvank** [comment]
@n1rna Agreed
